"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { bearerToken, neonClient } from "./neon-auth";

type Account={id:string;name:string;domain:string;category:string;tier:string;last_seen_at:string|null};
export default function Home() {
  const [accounts,setAccounts]=useState<Account[]>([]); const [loading,setLoading]=useState(true); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState<string|null>(null); const [signedIn,setSignedIn]=useState(false);
  const load=useCallback(async()=>{const token=await bearerToken();if(!token){setSignedIn(false);setLoading(false);return;}const response=await fetch("/api/accounts",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok){setError("Your session could not load accounts. Please sign in again.");setLoading(false);return;}setAccounts(await response.json());setSignedIn(true);setLoading(false);},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer);},[load]);
  async function signIn(event:FormEvent){event.preventDefault();setLoading(true);setError(null);try{const result=await (neonClient.auth as any).signInWithPassword({email,password});if(result?.error)throw new Error(result.error.message??"Sign-in failed");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Sign-in failed");setLoading(false);}}
  if(!signedIn)return <main className="mx-auto max-w-2xl px-6 py-24"><Badge variant="secondary">Neon Auth protected</Badge><h1 className="mt-4 text-5xl font-semibold tracking-tight">Bring your life admin together.</h1><p className="mt-4 text-muted-foreground">Sign in to see services discovered from your AgentMail inbox. The dashboard never reads a mailbox in the browser.</p><Card className="mt-8"><CardHeader><CardTitle>Sign in</CardTitle><CardDescription>Your session is issued by Neon Auth and is required by the API.</CardDescription></CardHeader><CardContent><form className="grid gap-4" onSubmit={signIn}><Input aria-label="Email" value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com" required/><Input aria-label="Password" value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" required/>{error&&<p className="text-sm text-destructive">{error}</p>}<Button disabled={loading} type="submit">{loading?"Checking session…":"Continue"}</Button></form></CardContent></Card></main>;
  return <main className="mx-auto max-w-6xl px-6 py-16"><Badge variant="secondary">Live discovery</Badge><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-5xl font-semibold tracking-tight">Your real accounts, discovered from mail.</h1><p className="mt-3 max-w-2xl text-muted-foreground">AgentMail is checked every 20 seconds. Services are classified through Neon AI Gateway and persisted in Neon Postgres.</p></div><Button variant="outline" onClick={()=>void load()}>Refresh</Button></div><section className="mt-10 grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Discovered services</CardDescription><CardTitle className="text-3xl">{accounts.length}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Polling</CardDescription><CardTitle>Every 20 seconds</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Data path</CardDescription><CardTitle>AgentMail → Neon</CardTitle></CardHeader></Card></section><section className="mt-10"><h2 className="text-2xl font-semibold">Accounts requiring review</h2><div className="mt-4 grid gap-3">{accounts.length===0?<Card><CardContent className="py-6 text-muted-foreground">No accounts found yet. New AgentMail messages will appear here after the next discovery pass.</CardContent></Card>:accounts.map(account=><Card key={account.id}><CardContent className="flex items-center justify-between gap-4 py-5"><div><h3 className="font-medium">{account.name}</h3><p className="mt-1 text-sm text-muted-foreground">{account.category} · {account.domain}</p></div><Badge variant={account.tier==="assist"?"destructive":"secondary"}>{account.tier}</Badge></CardContent></Card>)}</div></section></main>;
}