"use client";

import { useCallback, useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { bearerToken, neonClient } from "./neon-auth";

type Account={id:string;name:string;domain:string;category:string;tier:string;last_seen_at:string|null};
export default function Home() {
  const [accounts,setAccounts]=useState<Account[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [signedIn,setSignedIn]=useState(false);
  const load=useCallback(async()=>{const token=await bearerToken();if(!token){setSignedIn(false);setLoading(false);return;}const response=await fetch("/api/accounts",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok){setError("We could not load your accounts. Please sign in again.");setLoading(false);return;}setAccounts(await response.json());setSignedIn(true);setLoading(false);},[]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer);},[load]);
  async function signInWithGoogle(){setLoading(true);setError(null);try{const result=await (neonClient.auth as any).signIn.social({provider:"google",callbackURL:window.location.origin});if(result?.error)throw new Error(result.error.message??"Google sign-in could not start");}catch(reason){setError(reason instanceof Error?reason.message:"Google sign-in could not start");setLoading(false);}}
  if(!signedIn)return <main className="mx-auto max-w-2xl px-6 py-24"><Badge variant="secondary">Connected inbox</Badge><h1 className="mt-4 text-5xl font-semibold tracking-tight">See the services that need your attention.</h1><p className="mt-4 text-lg text-muted-foreground">We find bills, memberships, and subscriptions in your AgentMail inbox, then organize them into one review queue. Nothing changes without your approval.</p><Card className="mt-8"><CardHeader><CardTitle>Sign in to review your inbox</CardTitle><CardDescription>Use Google to securely open your personal review queue.</CardDescription></CardHeader><CardContent className="grid gap-3">{error&&<p className="text-sm text-destructive">{error}</p>}<Button disabled={loading} type="button" onClick={()=>void signInWithGoogle()}>{loading?"Checking your session…":"Continue with Google"}</Button></CardContent></Card></main>;
  return <main className="mx-auto max-w-6xl px-6 py-16"><Badge variant="secondary">Live discovery</Badge><div className="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-5xl font-semibold tracking-tight">Services found in your inbox.</h1><p className="mt-3 max-w-2xl text-muted-foreground">AgentMail is checked every 20 seconds. Services are classified through Neon AI Gateway and stored in Neon Postgres for your review.</p></div><Button variant="outline" onClick={()=>void load()}>Refresh</Button></div><section className="mt-10 grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Discovered services</CardDescription><CardTitle className="text-3xl">{accounts.length}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Inbox checks</CardDescription><CardTitle>Every 20 seconds</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Next step</CardDescription><CardTitle>Review changes</CardTitle></CardHeader></Card></section><section className="mt-10"><h2 className="text-2xl font-semibold">Accounts to review</h2><div className="mt-4 grid gap-3">{accounts.length===0?<Card><CardContent className="py-6 text-muted-foreground">No accounts found yet. New AgentMail messages will appear here after the next discovery pass.</CardContent></Card>:accounts.map(account=><Card key={account.id}><CardContent className="flex items-center justify-between gap-4 py-5"><div><h3 className="font-medium">{account.name}</h3><p className="mt-1 text-sm text-muted-foreground">{account.category} · {account.domain}</p></div><Badge variant={account.tier==="assist"?"destructive":"secondary"}>{account.tier}</Badge></CardContent></Card>)}</div></section></main>;
}